//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.14 at 01:00:41 AM MSK 
//

package ru.project.cscm.integration.model;

import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the ru.project.cscm.integration.model package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private static final ObjectFactory instance = new ObjectFactory();

    /**
     * Create a new ObjectFactory that can be used to create new instances of
     * schema derived classes for package: ru.project.cscm.integration.model
     * 
     */
    public ObjectFactory() {
    }

    @NotNull
    public static ObjectFactory get() {
        return instance;
    }

    /**
     * Create an instance of {@link DeliveryReport }
     * 
     */
    public DeliveryReport createDeliveryReport() {
        return new DeliveryReport();
    }
    
    /**
     * Create an instance of {@link DeliveryReport }
     * 
     */
    public DeliveryReport createErrorDeliveryReport(final String info) {
        final DeliveryReport report = this.createDeliveryReport();
        report.setVersion("1.0");
        report.setState("Error");
        report.setInfo(info);
        
        return report;
    }
    
    /**
     * Create an instance of {@link DeliveryReport }
     * 
     */
    public DeliveryReport createSuccessDeliveryReport() {
        final DeliveryReport report = this.createDeliveryReport();
        report.setVersion("1.0");
        report.setState("Success");
        
        return report;
    }
}
