//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.21 at 04:40:54 PM MSK 
//


package ru.project.cscm.monitoring.integration.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for AtmMonitoringStatisticsItem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AtmMonitoringStatisticsItem">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="atmInfo" type="{}AtmInfo"/>
 *         &lt;element name="encashmentInfo" type="{}EncashmentInfo"/>
 *         &lt;element name="cashInCassette" type="{}CashInCassetteInfo"/>
 *         &lt;element name="cashInRecyclingCassettes">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice maxOccurs="unbounded">
 *                   &lt;element name="cashInRecyclingCassette" type="{}CashInRecyclingCassetteInfo"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="cashOutCassettes">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice maxOccurs="4" minOccurs="4">
 *                   &lt;element name="cashOutCassette" type="{}CashOutCassetteInfo"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="transactionsByHours">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice maxOccurs="24" minOccurs="24">
 *                   &lt;element name="transactionsByHour" type="{}TransactionsStatistics"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="lastCashOutDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="lastCashInDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="statDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="avgTransactionsInDay" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="isIncidentExists" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="dateToCurrencyEnd" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="atmState">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="OPENED"/>
 *               &lt;enumeration value="CLOSED"/>
 *               &lt;enumeration value="DISCONNECTED"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="atmProblem">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="CARD_READER"/>
 *               &lt;enumeration value="RECEIPT_PRINTER"/>
 *               &lt;enumeration value="DISPENSER"/>
 *               &lt;enumeration value="BILL_ACCEPTOR"/>
 *               &lt;enumeration value="JOURNAL_PRINTER"/>
 *               &lt;enumeration value="IS_FULL"/>
 *               &lt;enumeration value="FIREWALL"/>
 *               &lt;enumeration value="NONE"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AtmMonitoringStatisticsItem", propOrder = {

})
public class AtmMonitoringStatisticsItem {

    @XmlElement(required = true)
    protected AtmInfo atmInfo;
    @XmlElement(required = true)
    protected EncashmentInfo encashmentInfo;
    @XmlElement(required = true)
    protected CashInCassetteInfo cashInCassette;
    @XmlElement(required = true)
    protected AtmMonitoringStatisticsItem.CashInRecyclingCassettes cashInRecyclingCassettes;
    @XmlElement(required = true)
    protected AtmMonitoringStatisticsItem.CashOutCassettes cashOutCassettes;
    @XmlElement(required = true)
    protected AtmMonitoringStatisticsItem.TransactionsByHours transactionsByHours;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastCashOutDate;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastCashInDate;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar statDate;
    protected int avgTransactionsInDay;
    protected boolean isIncidentExists;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateToCurrencyEnd;
    @XmlElement(required = true)
    protected String atmState;
    @XmlElement(required = true)
    protected String atmProblem;

    /**
     * Gets the value of the atmInfo property.
     * 
     * @return
     *     possible object is
     *     {@link AtmInfo }
     *     
     */
    public AtmInfo getAtmInfo() {
        return atmInfo;
    }

    /**
     * Sets the value of the atmInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link AtmInfo }
     *     
     */
    public void setAtmInfo(AtmInfo value) {
        this.atmInfo = value;
    }

    /**
     * Gets the value of the encashmentInfo property.
     * 
     * @return
     *     possible object is
     *     {@link EncashmentInfo }
     *     
     */
    public EncashmentInfo getEncashmentInfo() {
        return encashmentInfo;
    }

    /**
     * Sets the value of the encashmentInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link EncashmentInfo }
     *     
     */
    public void setEncashmentInfo(EncashmentInfo value) {
        this.encashmentInfo = value;
    }

    /**
     * Gets the value of the cashInCassette property.
     * 
     * @return
     *     possible object is
     *     {@link CashInCassetteInfo }
     *     
     */
    public CashInCassetteInfo getCashInCassette() {
        return cashInCassette;
    }

    /**
     * Sets the value of the cashInCassette property.
     * 
     * @param value
     *     allowed object is
     *     {@link CashInCassetteInfo }
     *     
     */
    public void setCashInCassette(CashInCassetteInfo value) {
        this.cashInCassette = value;
    }

    /**
     * Gets the value of the cashInRecyclingCassettes property.
     * 
     * @return
     *     possible object is
     *     {@link AtmMonitoringStatisticsItem.CashInRecyclingCassettes }
     *     
     */
    public AtmMonitoringStatisticsItem.CashInRecyclingCassettes getCashInRecyclingCassettes() {
        return cashInRecyclingCassettes;
    }

    /**
     * Sets the value of the cashInRecyclingCassettes property.
     * 
     * @param value
     *     allowed object is
     *     {@link AtmMonitoringStatisticsItem.CashInRecyclingCassettes }
     *     
     */
    public void setCashInRecyclingCassettes(AtmMonitoringStatisticsItem.CashInRecyclingCassettes value) {
        this.cashInRecyclingCassettes = value;
    }

    /**
     * Gets the value of the cashOutCassettes property.
     * 
     * @return
     *     possible object is
     *     {@link AtmMonitoringStatisticsItem.CashOutCassettes }
     *     
     */
    public AtmMonitoringStatisticsItem.CashOutCassettes getCashOutCassettes() {
        return cashOutCassettes;
    }

    /**
     * Sets the value of the cashOutCassettes property.
     * 
     * @param value
     *     allowed object is
     *     {@link AtmMonitoringStatisticsItem.CashOutCassettes }
     *     
     */
    public void setCashOutCassettes(AtmMonitoringStatisticsItem.CashOutCassettes value) {
        this.cashOutCassettes = value;
    }

    /**
     * Gets the value of the transactionsByHours property.
     * 
     * @return
     *     possible object is
     *     {@link AtmMonitoringStatisticsItem.TransactionsByHours }
     *     
     */
    public AtmMonitoringStatisticsItem.TransactionsByHours getTransactionsByHours() {
        return transactionsByHours;
    }

    /**
     * Sets the value of the transactionsByHours property.
     * 
     * @param value
     *     allowed object is
     *     {@link AtmMonitoringStatisticsItem.TransactionsByHours }
     *     
     */
    public void setTransactionsByHours(AtmMonitoringStatisticsItem.TransactionsByHours value) {
        this.transactionsByHours = value;
    }

    /**
     * Gets the value of the lastCashOutDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastCashOutDate() {
        return lastCashOutDate;
    }

    /**
     * Sets the value of the lastCashOutDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastCashOutDate(XMLGregorianCalendar value) {
        this.lastCashOutDate = value;
    }

    /**
     * Gets the value of the lastCashInDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastCashInDate() {
        return lastCashInDate;
    }

    /**
     * Sets the value of the lastCashInDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastCashInDate(XMLGregorianCalendar value) {
        this.lastCashInDate = value;
    }

    /**
     * Gets the value of the statDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStatDate() {
        return statDate;
    }

    /**
     * Sets the value of the statDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStatDate(XMLGregorianCalendar value) {
        this.statDate = value;
    }

    /**
     * Gets the value of the avgTransactionsInDay property.
     * 
     */
    public int getAvgTransactionsInDay() {
        return avgTransactionsInDay;
    }

    /**
     * Sets the value of the avgTransactionsInDay property.
     * 
     */
    public void setAvgTransactionsInDay(int value) {
        this.avgTransactionsInDay = value;
    }

    /**
     * Gets the value of the isIncidentExists property.
     * 
     */
    public boolean isIsIncidentExists() {
        return isIncidentExists;
    }

    /**
     * Sets the value of the isIncidentExists property.
     * 
     */
    public void setIsIncidentExists(boolean value) {
        this.isIncidentExists = value;
    }

    /**
     * Gets the value of the dateToCurrencyEnd property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateToCurrencyEnd() {
        return dateToCurrencyEnd;
    }

    /**
     * Sets the value of the dateToCurrencyEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateToCurrencyEnd(XMLGregorianCalendar value) {
        this.dateToCurrencyEnd = value;
    }

    /**
     * Gets the value of the atmState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAtmState() {
        return atmState;
    }

    /**
     * Sets the value of the atmState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAtmState(String value) {
        this.atmState = value;
    }

    /**
     * Gets the value of the atmProblem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAtmProblem() {
        return atmProblem;
    }

    /**
     * Sets the value of the atmProblem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAtmProblem(String value) {
        this.atmProblem = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice maxOccurs="unbounded">
     *         &lt;element name="cashInRecyclingCassette" type="{}CashInRecyclingCassetteInfo"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "cashInRecyclingCassette"
    })
    public static class CashInRecyclingCassettes {

        protected List<CashInRecyclingCassetteInfo> cashInRecyclingCassette;

        /**
         * Gets the value of the cashInRecyclingCassette property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the cashInRecyclingCassette property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCashInRecyclingCassette().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CashInRecyclingCassetteInfo }
         * 
         * 
         */
        public List<CashInRecyclingCassetteInfo> getCashInRecyclingCassette() {
            if (cashInRecyclingCassette == null) {
                cashInRecyclingCassette = new ArrayList<CashInRecyclingCassetteInfo>();
            }
            return this.cashInRecyclingCassette;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice maxOccurs="4" minOccurs="4">
     *         &lt;element name="cashOutCassette" type="{}CashOutCassetteInfo"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "cashOutCassette"
    })
    public static class CashOutCassettes {

        protected List<CashOutCassetteInfo> cashOutCassette;

        /**
         * Gets the value of the cashOutCassette property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the cashOutCassette property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCashOutCassette().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CashOutCassetteInfo }
         * 
         * 
         */
        public List<CashOutCassetteInfo> getCashOutCassette() {
            if (cashOutCassette == null) {
                cashOutCassette = new ArrayList<CashOutCassetteInfo>();
            }
            return this.cashOutCassette;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice maxOccurs="24" minOccurs="24">
     *         &lt;element name="transactionsByHour" type="{}TransactionsStatistics"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "transactionsByHour"
    })
    public static class TransactionsByHours {

        protected List<TransactionsStatistics> transactionsByHour;

        /**
         * Gets the value of the transactionsByHour property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the transactionsByHour property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTransactionsByHour().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TransactionsStatistics }
         * 
         * 
         */
        public List<TransactionsStatistics> getTransactionsByHour() {
            if (transactionsByHour == null) {
                transactionsByHour = new ArrayList<TransactionsStatistics>();
            }
            return this.transactionsByHour;
        }

    }

}
