//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.21 at 04:40:54 PM MSK 
//


package ru.project.cscm.monitoring.integration.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for CashOutCassetteInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CashOutCassetteInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="denomination" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="isWorking" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="currency" type="{}Currency"/>
 *         &lt;element name="number" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="remaining" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="uploaded" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="notesCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="demand" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="exhaustionDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CashOutCassetteInfo", propOrder = {

})
public class CashOutCassetteInfo {

    protected int denomination;
    protected boolean isWorking;
    @XmlElement(required = true)
    protected Currency currency;
    protected int number;
    protected int remaining;
    protected int uploaded;
    protected int notesCount;
    protected int demand;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar exhaustionDate;

    /**
     * Gets the value of the denomination property.
     * 
     */
    public int getDenomination() {
        return denomination;
    }

    /**
     * Sets the value of the denomination property.
     * 
     */
    public void setDenomination(int value) {
        this.denomination = value;
    }

    /**
     * Gets the value of the isWorking property.
     * 
     */
    public boolean isIsWorking() {
        return isWorking;
    }

    /**
     * Sets the value of the isWorking property.
     * 
     */
    public void setIsWorking(boolean value) {
        this.isWorking = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link Currency }
     *     
     */
    public Currency getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link Currency }
     *     
     */
    public void setCurrency(Currency value) {
        this.currency = value;
    }

    /**
     * Gets the value of the number property.
     * 
     */
    public int getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     * 
     */
    public void setNumber(int value) {
        this.number = value;
    }

    /**
     * Gets the value of the remaining property.
     * 
     */
    public int getRemaining() {
        return remaining;
    }

    /**
     * Sets the value of the remaining property.
     * 
     */
    public void setRemaining(int value) {
        this.remaining = value;
    }

    /**
     * Gets the value of the uploaded property.
     * 
     */
    public int getUploaded() {
        return uploaded;
    }

    /**
     * Sets the value of the uploaded property.
     * 
     */
    public void setUploaded(int value) {
        this.uploaded = value;
    }

    /**
     * Gets the value of the notesCount property.
     * 
     */
    public int getNotesCount() {
        return notesCount;
    }

    /**
     * Sets the value of the notesCount property.
     * 
     */
    public void setNotesCount(int value) {
        this.notesCount = value;
    }

    /**
     * Gets the value of the demand property.
     * 
     */
    public int getDemand() {
        return demand;
    }

    /**
     * Sets the value of the demand property.
     * 
     */
    public void setDemand(int value) {
        this.demand = value;
    }

    /**
     * Gets the value of the exhaustionDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getExhaustionDate() {
        return exhaustionDate;
    }

    /**
     * Sets the value of the exhaustionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setExhaustionDate(XMLGregorianCalendar value) {
        this.exhaustionDate = value;
    }

}
