//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.21 at 04:40:54 PM MSK 
//


package ru.project.cscm.monitoring.integration.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for EncashmentInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EncashmentInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="encashmentPlannedDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="lastEncashmentDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="isExpress" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="encashmentSumm" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EncashmentInfo", propOrder = {

})
public class EncashmentInfo {

    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar encashmentPlannedDate;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar lastEncashmentDate;
    protected boolean isExpress;
    protected double encashmentSumm;

    /**
     * Gets the value of the encashmentPlannedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEncashmentPlannedDate() {
        return encashmentPlannedDate;
    }

    /**
     * Sets the value of the encashmentPlannedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEncashmentPlannedDate(XMLGregorianCalendar value) {
        this.encashmentPlannedDate = value;
    }

    /**
     * Gets the value of the lastEncashmentDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastEncashmentDate() {
        return lastEncashmentDate;
    }

    /**
     * Sets the value of the lastEncashmentDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastEncashmentDate(XMLGregorianCalendar value) {
        this.lastEncashmentDate = value;
    }

    /**
     * Gets the value of the isExpress property.
     * 
     */
    public boolean isIsExpress() {
        return isExpress;
    }

    /**
     * Sets the value of the isExpress property.
     * 
     */
    public void setIsExpress(boolean value) {
        this.isExpress = value;
    }

    /**
     * Gets the value of the encashmentSumm property.
     * 
     */
    public double getEncashmentSumm() {
        return encashmentSumm;
    }

    /**
     * Sets the value of the encashmentSumm property.
     * 
     */
    public void setEncashmentSumm(double value) {
        this.encashmentSumm = value;
    }

}
